[build]
  base = "frontend"
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
